name: PR-BOT

on:
  pull_request_target:

jobs:
  review-pull-request:
    name: Review Pull Request
    env:
      FORCE_COLOR: 1
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check signed commits
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
